### ISSUE TITLE
css_to_xpath throws error when css class name starts with a number

### ISSUE THREAD

**Issue by Yeedle** [sjp/selectr#6]
When using the `css_to_xpath` function, passing it a class selector name that starts with a number, causes an error.

```r
selectr::css_to_xpath('.1u')
> Error in parse_simple_selector(stream) : 
> Expected selector, got <NUMBER '.1' at 1>
```

Doing the same for an id, works perfectly fine.
```r
selectr::css_to_xpath('#1u')
> [1] "descendant-or-self::*[@id = '1u']"
```

**Comment by sjp** [comment]
Hi,

Looks like you've hit behaviour which is unintuitive, but correct according to the [selectors specification](https://www.w3.org/TR/selectors/#lex).

A selector for an ID is allowed to start with the following characters: `_a-z0-9-`. However, class selectors are only permitted to start with these characters: `_a-z`.

Rather than change `selectr` to be non-conformant to the CSS selector spec, how about a workaround:

``` r
> selectr::css_to_xpath(".asdf")
[1] "descendant-or-self::*[@class and contains(concat(' ', normalize-space(@class), ' '), ' asdf ')]"
```

Then modify the output so that instead of `asdf` you have `1u`.

Here's a simple function which can perform this task for you. Hopefully this is sufficient for your needs.

``` r
> unsafeClassSelector <- function(className) {
+     dummyClassName <- rep_len("asdf", length(className))
+     css <- selectr::css_to_xpath(paste0(".", dummyClassName))
+     sapply(seq_along(className), function(i) {
+         gsub(dummyClassName[i], className[i], css[i], fixed = TRUE)
+     }, USE.NAMES = FALSE)
+ }
> 
> unsafeClassSelector("1u")
[1] "descendant-or-self::*[@class and contains(concat(' ', normalize-space(@class), ' '), ' 1u ')]"
```

**Comment by Yeedle** [comment]
Fair enough. Thanks for the helper function!
